<a href="https://colab.research.google.com/github/devmofizur/Python/blob/main/Pandas/Dataset%20and%20manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Importing csv file**

In [37]:
from google.colab import drive
import shutil
import os

drive.mount('/content/drive')

source_path = '/content/drive/MyDrive/Colab Notebooks/movies.csv'
destination_path = '/content/movies.csv'

if os.path.exists(source_path):
    shutil.copy(source_path, destination_path)
    print(f"Successfully copied '{source_path}' to '{destination_path}'")
else:
    print(f"Error: Source file '{source_path}' not found.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Successfully copied '/content/drive/MyDrive/Colab Notebooks/movies.csv' to '/content/movies.csv'

In [38]:
path = '/content/movies.csv'

# **Rating using python list**

In [39]:
import csv

In [40]:
def rating_status_calculation(data, industry = None):
  rating = []
  for row in data:
    if row[3]!= 'NULL' and (not industry or row[1] == industry):
      rating.append(float(row[3]))
  min_rating = min(rating)
  max_rating = max(rating)
  avg_rating = sum(rating)/len(rating)
  return min_rating, max_rating, avg_rating

In [41]:
def get_industries(data):
  industries =[]
  for row in data:
    if row[1] not in industries:
      industries.append(row[1])
  return industries

In [42]:
with open(path, 'r') as file:
    reader = list(csv.reader(file))
    header = reader[0]
    data = reader[1:]
print(header)
print(data[0])

['title', 'industry', 'release_year', 'imdb_rating', 'studio', 'budget', 'revenue', 'unit', 'currency', 'language']
['Pather Panchali', 'Bollywood', '1955', '8.3', 'Government of West Bengal', '70000', '100000', 'Thousands', 'INR', 'Bengali']

In [43]:
get_industries(data)

['Bollywood', 'Hollywood']

In [44]:
b_min, b_max, b_avg =rating_status_calculation(data, industry='Bollywood')
print(f"Bollywood ratings : min {b_min} , max {b_max} , avg {b_avg}")

h_min, h_max, h_avg = rating_status_calculation(data, industry='Hollywood')
print(f"Hollywood ratings : min {h_min} , max {h_max} , avg {h_avg}")

o_min, o_max, o_avg =rating_status_calculation(data)
print(f"Overall ratings : min {o_min} , max {o_max} , avg {o_avg}")

Bollywood ratings : min 1.9 , max 8.4 , avg 7.65625
Hollywood ratings : min 6.8 , max 9.3 , avg 8.129999999999999
Overall ratings : min 1.9 , max 9.3 , avg 7.919444444444445

#**Rating with Pandas**

In [45]:
import pandas as pd

In [46]:
df = pd.read_csv(path)
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English

In [47]:
df.tail()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.0,950.0,Millions,INR,Hindi
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.0,12.5,Billions,INR,Kannada
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.0,3.6,Billions,INR,Telugu
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.8,6.5,Billions,INR,Telugu

In [48]:
df.sample(4)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,Hindi
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.00,2000.0,Millions,INR,Hindi
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.00,1006.0,Millions,USD,English
10,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English

In [49]:
df.shape

(37, 10)

In [50]:
df['industry'].unique()

array(['Bollywood', 'Hollywood'], dtype=object)

In [51]:
df['imdb_rating']

0     8.3
1     7.0
2     6.8
3     7.9
4     6.8
5     9.3
6     8.6
7     8.0
8     8.5
9     7.9
10    8.6
11    7.8
12    9.2
13    9.0
14    9.0
15    8.2
16    8.5
17    8.4
18    8.4
19    6.9
20    7.8
21    8.0
22    8.4
23    7.4
24    7.2
25    8.3
26    8.1
27    8.1
28    NaN
29    8.3
30    8.1
31    1.9
32    8.4
33    8.4
34    7.6
35    8.0
36    8.0
Name: imdb_rating, dtype: float64

In [52]:
type(df)

pandas.core.frame.DataFrame

In [53]:
type(df.imdb_rating)

pandas.core.series.Series

**Printing min, max, mean rating**

In [54]:
df.imdb_rating.min() , df.imdb_rating.max() , float(df.imdb_rating.mean())

(1.9, 9.3, 7.919444444444445)

In [55]:
df_b = df[df.industry == 'Bollywood']
df_b.imdb_rating.min() , df_b.imdb_rating.max() , float(df_b.imdb_rating.mean())

(1.9, 8.4, 7.656250000000001)

In [56]:
df_h = df[df.industry == 'Hollywood']
df_h.imdb_rating.min() , df_h.imdb_rating.max() , float(df_h.imdb_rating.mean())

(6.8, 9.3, 8.130000000000003)

In [57]:
df.groupby('industry').imdb_rating.agg(['min', 'max', 'mean'])

           min  max     mean
industry
Bollywood  1.9  8.4  7.65625
Hollywood  6.8  9.3  8.13000

# **Dataset Analysis**

In [58]:
df.language.unique()

array(['Bengali', 'English', 'Hindi', 'Kannada', 'Telugu'], dtype=object)

In [59]:
df.groupby('industry').language.value_counts()

industry   language
Bollywood  Hindi       12
           Telugu       3
           Bengali      1
           Kannada      1
Hollywood  English     20
Name: count, dtype: int64

In [60]:
df[['title',	'industry',	'release_year'	,'imdb_rating'	]]

,title,industry,release_year,imdb_rating
0,Pather Panchali,Bollywood,1955,8.3
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0
2,Thor: The Dark World,Hollywood,2013,6.8
3,Thor: Ragnarok,Hollywood,2017,7.9
4,Thor: Love and Thunder,Hollywood,2022,6.8
5,The Shawshank Redemption,Hollywood,1994,9.3
6,Interstellar,Hollywood,2014,8.6
7,The Pursuit of Happyness,Hollywood,2006,8.0
8,Gladiator,Hollywood,2000,8.5
9,Titanic,Hollywood,1997,7.9
10,It's a Wonderful Life,Hollywood,1946,8.6
11,Avatar,Hollywood,2009,7.8
12,The Godfather,Hollywood,1972,9.2
13,The Dark Knight,Hollywood,2008,9.0
14,Schindler's List,Hollywood,1993,9.0
15,Jurassic Park,Hollywood,1993,8.2
16,Parasite,Hollywood,2019,8.5
17,Avengers: Endgame,Hollywood,2019,8.4
18,Avengers: Infinity War,Hollywood,2018,8.4
19,Captain America: The First Avenger,Hollywood,2011,6.9
20,Captain America: The Winter Soldier,Hollywood,2014,7.8
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0
22,3 Idiots,Bollywood,2009,8.4
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4
24,Bajirao Mastani,Bollywood,2015,7.2
25,Taare Zameen Par,Bollywood,2007,8.3
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1
27,PK,Bollywood,2014,8.1
28,Sanju,Bollywood,2018,NaN
29,The Kashmir Files,Bollywood,2022,8.3
30,Bajrangi Bhaijaan,Bollywood,2015,8.1
31,Race 3,Bollywood,2018,1.9
32,Shershaah,Bollywood,2021,8.4
33,K.G.F: Chapter 2,Bollywood,2022,8.4
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6
35,RRR,Bollywood,2022,8.0
36,Baahubali: The Beginning,Bollywood,2015,8.0

In [61]:
df[(df.release_year > 2000) & (df.studio == 'Marvel Studios')].sort_values('release_year', ascending=True)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.7,370.6,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.0,714.4,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.0,2048.0,Millions,USD,English
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.0,2798.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English

In [62]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
release_year,37.0,2007.027027,17.657995,1946.0,2001.0,2014.0,2018.0,2022.0
imdb_rating,36.0,7.919444,1.204947,1.9,7.8,8.1,8.4,9.3
budget,37.0,2084.975135,11477.487145,1.0,15.5,165.0,250.0,70000.0
revenue,37.0,4117.135135,16372.462682,3.1,263.1,701.8,2000.0,100000.0

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         37 non-null     object
 1   industry      37 non-null     object
 2   release_year  37 non-null     int64
 3   imdb_rating   36 non-null     float64
 4   studio        34 non-null     object
 5   budget        37 non-null     float64
 6   revenue       37 non-null     float64
 7   unit          37 non-null     object
 8   currency      37 non-null     object
 9   language      37 non-null     object
dtypes: float64(3), int64(1), object(6)
memory usage: 3.0+ KB

In [64]:
df.isnull().sum()

title           0
industry        0
release_year    0
imdb_rating     1
studio          3
budget          0
revenue         0
unit            0
currency        0
language        0
dtype: int64

In [65]:
df.imdb_rating.max()

9.3

In [66]:
df[(df.imdb_rating == df.imdb_rating.min()) | (df.imdb_rating == df.imdb_rating.max())]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.8,3.1,Billions,INR,Hindi

In [67]:
df.age = df.release_year.apply(lambda x: 2026 - x) # x = all individual values of release_year column + df.age = visualize not actually adding it to main dataframe
df.head()

/tmp/ipykernel_17686/1285861204.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.age = df.release_year.apply(lambda x: 2026 - x) # x = all individual values of release_year column + df.age = visualize not actually adding it to main dataframe

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English

In [68]:
df['age'] = df.release_year.apply(lambda x: 2026 - x) # df['age'] actually adds to dataframe
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,71
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,4
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,9
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,4

In [69]:
df.profit = df.apply(lambda x : x.revenue - x.budget, axis = 1) # by default axis = 0
# axis = 0 means rowwise operation and there is not attribute named revenue or budget  in row.
# those and column or series names.
df.head()

/tmp/ipykernel_17686/2622320325.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.profit = df.apply(lambda x : x.revenue - x.budget, axis = 1) # by default axis = 0

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,71
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,4
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,9
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,4

In [70]:
df['profit'] = df.apply(lambda x : x.revenue - x.budget, axis = 1)
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,71,30000.0
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,4,754.8
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13,479.8
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,9,674.0
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,4,420.0

## **Index shifting**

In [71]:
df.index

RangeIndex(start=0, stop=37, step=1)

In [72]:
df.set_index('title', inplace=True)
df.head()

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
title,,,,,,,,,,,
Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,71,30000.0
Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,4,754.8
Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13,479.8
Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,9,674.0
Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,4,420.0

In [73]:
df.index

Index(['Pather Panchali', 'Doctor Strange in the Multiverse of Madness',
       'Thor: The Dark World ', 'Thor: Ragnarok ', 'Thor: Love and Thunder ',
       'The Shawshank Redemption', 'Interstellar', 'The Pursuit of Happyness',
       'Gladiator', 'Titanic', 'It's a Wonderful Life', 'Avatar',
       'The Godfather', 'The Dark Knight', 'Schindler's List', 'Jurassic Park',
       'Parasite', 'Avengers: Endgame', 'Avengers: Infinity War',
       'Captain America: The First Avenger',
       'Captain America: The Winter Soldier', 'Dilwale Dulhania Le Jayenge',
       '3 Idiots', 'Kabhi Khushi Kabhie Gham', 'Bajirao Mastani ',
       'Taare Zameen Par', 'Munna Bhai M.B.B.S.', 'PK', 'Sanju',
       'The Kashmir Files', 'Bajrangi Bhaijaan', 'Race 3', 'Shershaah',
       'K.G.F: Chapter 2', 'Pushpa: The Rise - Part 1', 'RRR',
       'Baahubali: The Beginning'],
      dtype='object', name='title')

In [76]:
df.loc[['RRR','Avengers: Endgame']]

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
title,,,,,,,,,,,
RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu,4,6.5
Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.0,2798.0,Millions,USD,English,7,2398.0

In [83]:
df.iloc[0]

industry                        Bollywood
release_year                         1955
imdb_rating                           8.3
studio          Government of West Bengal
budget                            70000.0
revenue                          100000.0
unit                            Thousands
currency                              INR
language                          Bengali
age                                    71
profit                            30000.0
Name: Pather Panchali, dtype: object

In [84]:
df.reset_index(inplace=True)
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,71,30000.0
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,4,754.8
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13,479.8
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,9,674.0
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,4,420.0