<a href="https://colab.research.google.com/github/devmofizur/Python/blob/main/Pandas/Data_Concatenation_and_Merging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
data1 = pd.DataFrame({
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'total_house': [350000, 420000, 280000, 310000, 250000],
    'total_hotels': [300, 450, 200, 280, 150]
})

data2 = pd.DataFrame({
    'city': ['Bhola','Shylhet', 'Dinajpur','Feni','Jessore'],
    'total_house': [20000, 38000, 15000, 40000, 9000],
    'total_hotels': [100, 350, 80, 400, 60]
})

In [3]:
df = pd.concat([data1,data2])
df

          city  total_house  total_hotels
0     New York       350000           300
1  Los Angeles       420000           450
2      Chicago       280000           200
3      Houston       310000           280
4      Phoenix       250000           150
0        Bhola        20000           100
1      Shylhet        38000           350
2     Dinajpur        15000            80
3         Feni        40000           400
4      Jessore         9000            60

In [4]:
df = pd.concat([data1,data2], ignore_index=True)
df

          city  total_house  total_hotels
0     New York       350000           300
1  Los Angeles       420000           450
2      Chicago       280000           200
3      Houston       310000           280
4      Phoenix       250000           150
5        Bhola        20000           100
6      Shylhet        38000           350
7     Dinajpur        15000            80
8         Feni        40000           400
9      Jessore         9000            60

In [5]:
df = pd.concat([data1,data2], keys = ['US', 'BD'])
df

             city  total_house  total_hotels
US 0     New York       350000           300
   1  Los Angeles       420000           450
   2      Chicago       280000           200
   3      Houston       310000           280
   4      Phoenix       250000           150
BD 0        Bhola        20000           100
   1      Shylhet        38000           350
   2     Dinajpur        15000            80
   3         Feni        40000           400
   4      Jessore         9000            60

In [6]:
df.loc['BD']

       city  total_house  total_hotels
0     Bhola        20000           100
1   Shylhet        38000           350
2  Dinajpur        15000            80
3      Feni        40000           400
4   Jessore         9000            60

In [7]:
df = pd.concat([data1,data2], keys = ['US', 'BD'], axis =1)
df

            US                                 BD
          city total_house total_hotels      city total_house total_hotels
0     New York      350000          300     Bhola       20000          100
1  Los Angeles      420000          450   Shylhet       38000          350
2      Chicago      280000          200  Dinajpur       15000           80
3      Houston      310000          280      Feni       40000          400
4      Phoenix      250000          150   Jessore        9000           60

In [16]:
data1 = pd.DataFrame({
    'city': ['London', 'Paris', 'Berlin', 'Rome', 'Madrid'],
    'average_temperature': [12, 15, 10, 18, 16],
    'average_humidity': [75, 70, 80, 65, 60]
})

data2 = pd.DataFrame({
    'city': ['Cairo', 'Dubai', 'Mumbai', 'Sydney', 'Tokyo'],
    'average_temperature': [25, 30, 28, 15, 19],
    'average_humidity': [50, 40, 70, 70, 68]
})

In [18]:
df3 = pd.merge(data1,data2, on = 'average_temperature') #SQL JOIN
df3

  city_x  average_temperature  average_humidity_x  city_y  average_humidity_y
0  Paris                   15                  70  Sydney                  70

## SQL JOIN

In [22]:
from IPython.display import Image
Image(url='https://www.red-gate.com/simple-talk/wp-content/uploads/2025/08/image-7.png')

In [53]:
data1 = pd.DataFrame({
    'item': ['Apple', 'Banana', 'Orange', 'Grape', 'Kiwi'],
    'price': [1.2, 0.5, 0.8, 2.0, 1.5],
    'quantity': [100, 250, 180, 70, 120]
})

data2 = pd.DataFrame({
    'item': ['Milk', 'Bread', 'Eggs', 'Grape', 'Butter'],
    'price': [3.0, 2.5, 4.0, 7.0, 5.0],
    'quantity': [50, 80, 60, 30, 40]
})

In [54]:
df4 = pd.merge(data1,data2,  how = 'outer')
df4

     item  price  quantity
0   Apple    1.2       100
1  Banana    0.5       250
2   Bread    2.5        80
3  Butter    5.0        40
4    Eggs    4.0        60
5   Grape    2.0        70
6   Grape    7.0        30
7    Kiwi    1.5       120
8    Milk    3.0        50
9  Orange    0.8       180

In [55]:
df4 = pd.merge(data1,data2, how = 'left')
df4

     item  price  quantity
0   Apple    1.2       100
1  Banana    0.5       250
2  Orange    0.8       180
3   Grape    2.0        70
4    Kiwi    1.5       120

In [57]:
df4 = pd.merge(data1, data2,  how='right')
df4

     item  price  quantity
0    Milk    3.0        50
1   Bread    2.5        80
2    Eggs    4.0        60
3   Grape    7.0        30
4  Butter    5.0        40

In [61]:
df4 = pd.merge(data1, data2, how='inner')
df4

Empty DataFrame
Columns: [item, price, quantity]
Index: []

In [62]:
df4 = pd.merge(data1,data2, on='item', how = 'outer')
df4

     item  price_x  quantity_x  price_y  quantity_y
0   Apple      1.2       100.0      NaN         NaN
1  Banana      0.5       250.0      NaN         NaN
2   Bread      NaN         NaN      2.5        80.0
3  Butter      NaN         NaN      5.0        40.0
4    Eggs      NaN         NaN      4.0        60.0
5   Grape      2.0        70.0      7.0        30.0
6    Kiwi      1.5       120.0      NaN         NaN
7    Milk      NaN         NaN      3.0        50.0
8  Orange      0.8       180.0      NaN         NaN

In [63]:
df4 = pd.merge(data1,data2, on='item', how = 'left')
df4

     item  price_x  quantity_x  price_y  quantity_y
0   Apple      1.2         100      NaN         NaN
1  Banana      0.5         250      NaN         NaN
2  Orange      0.8         180      NaN         NaN
3   Grape      2.0          70      7.0        30.0
4    Kiwi      1.5         120      NaN         NaN

In [64]:
df4 = pd.merge(data1,data2, on='item', how = 'right')
df4

     item  price_x  quantity_x  price_y  quantity_y
0    Milk      NaN         NaN      3.0          50
1   Bread      NaN         NaN      2.5          80
2    Eggs      NaN         NaN      4.0          60
3   Grape      2.0        70.0      7.0          30
4  Butter      NaN         NaN      5.0          40

In [65]:
df4 = pd.merge(data1,data2, on='item', how = 'inner')
df4

    item  price_x  quantity_x  price_y  quantity_y
0  Grape      2.0          70      7.0          30