<a href="https://colab.research.google.com/github/devmofizur/Python/blob/main/Pandas/Grouping_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Practice**

In [1]:
from google.colab import drive
import shutil
import os

drive.mount('/content/drive')

source_path = '/content/drive/MyDrive/Colab Notebooks/ML Learning/weather_by_cities.csv'
destination_path = '/content/weather_by_cities.csv'

if os.path.exists(source_path):
    shutil.copy(source_path, destination_path)
    print(f"Successfully copied '{source_path}' to '{destination_path}'")
else:
    print(f"Error: Source file '{source_path}' not found.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Successfully copied '/content/drive/MyDrive/Colab Notebooks/ML Learning/weather_by_cities.csv' to '/content/weather_by_cities.csv'

In [2]:
import pandas as pd

df = pd.read_csv('/content/weather_by_cities.csv')
df.head()

        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
4  1/1/2017    mumbai           90          5  Sunny

In [3]:
group_object = df.groupby('city')

In [4]:
for city,data in group_object:
  print(data)

        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

In [5]:
for city,data in group_object:
  print(city,"->",data.temperature.max())

mumbai -> 92
new york -> 36
paris -> 54

In [6]:
group_object.size()

city
mumbai      4
new york    4
paris       4
dtype: int64

In [15]:
def grouping(df,idx,column):
  if df[column][idx] > 86:
    return 'hot'
  elif df[column][idx] < 50:
    return 'cold'
  else:
    return 'warm'

In [16]:
group_object = df.groupby(lambda idx : grouping(df,idx, 'temperature'))

In [17]:
for key,data in group_object:
  print("Key : ", key)
  print("Data : ",data)

Key :  cold
Data :           day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
8   1/1/2017     paris           45         20   Sunny
11  1/4/2017     paris           42         10  Cloudy
Key :  hot
Data :          day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
Key :  warm
Data :           day    city  temperature  windspeed   event
5   1/2/2017  mumbai           85         12     Fog
9   1/2/2017   paris           50         13  Cloudy
10  1/3/2017   paris           54          8  Cloudy

## **Exercise** : [Question Link](https://drive.google.com/file/d/1JhG4ky2OWOeKisfi5PxskrECCnXBWl9F/view?usp=sharing)

In [18]:
from google.colab import drive
import shutil
import os

drive.mount('/content/drive')

source_path = '/content/drive/MyDrive/Colab Notebooks/ML Learning/movies_data.csv'
destination_path = '/content/movies_data.csv'

if os.path.exists(source_path):
    shutil.copy(source_path, destination_path)
    print(f"Successfully copied '{source_path}' to '{destination_path}'")
else:
    print(f"Error: Source file '{source_path}' not found.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Successfully copied '/content/drive/MyDrive/Colab Notebooks/ML Learning/movies_data.csv' to '/content/movies_data.csv'

In [19]:
import pandas as pd
df = pd.read_csv(destination_path)
df

,movie_id,title,industry,language,release_year,imdb_rating,studio,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,Kannada,2022,8.4,Hombale Films,1.00,12.5,Billions,INR
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,English,2022,7.0,Marvel Studios,200.00,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,English,2013,6.8,Marvel Studios,165.00,644.8,Millions,USD
3,104,Thor: Ragnarok,Hollywood,English,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD
4,105,Thor: Love and Thunder,Hollywood,English,2022,6.8,Marvel Studios,250.00,670.0,Millions,USD
5,111,The Shawshank Redemption,Hollywood,English,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD
6,113,Interstellar,Hollywood,English,2014,8.6,Warner Bros. Pictures,165.00,701.8,Millions,USD
7,115,The Pursuit of Happyness,Hollywood,English,2006,8.0,Columbia Pictures,55.00,307.1,Millions,USD
8,116,Gladiator,Hollywood,English,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD
9,117,Titanic,Hollywood,English,1997,7.9,Paramount Pictures,200.00,2202.0,Millions,USD
10,118,It's a Wonderful Life,Hollywood,English,1946,8.6,Liberty Films,3.18,3.3,Millions,USD
11,119,Avatar,Hollywood,English,2009,7.8,20th Century Fox,237.00,2847.0,Millions,USD
12,120,The Godfather,Hollywood,English,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD
13,121,The Dark Knight,Hollywood,English,2008,9.0,Syncopy,185.00,1006.0,Millions,USD
14,122,Schindler's List,Hollywood,English,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD
15,123,Jurassic Park,Hollywood,English,1993,8.2,Universal Pictures,63.00,1046.0,Millions,USD
16,124,Parasite,Hollywood,English,2019,8.5,NaN,15.50,263.1,Millions,USD
17,125,Avengers: Endgame,Hollywood,English,2019,8.4,Marvel Studios,400.00,2798.0,Millions,USD
18,126,Avengers: Infinity War,Hollywood,English,2018,8.4,Marvel Studios,400.00,2048.0,Millions,USD
19,137,Captain America: The First Avenger,Hollywood,English,2011,6.9,Marvel Studios,216.70,370.6,Millions,USD
20,138,Captain America: The Winter Soldier,Hollywood,English,2014,7.8,Marvel Studios,177.00,714.4,Millions,USD
21,107,Dilwale Dulhania Le Jayenge,Bollywood,Hindi,1995,8.0,Yash Raj Films,400.00,2000.0,Millions,INR
22,108,3 Idiots,Bollywood,Hindi,2009,8.4,Vinod Chopra Films,550.00,4000.0,Millions,INR
23,109,Kabhi Khushi Kabhie Gham,Bollywood,Hindi,2001,7.4,Dharma Productions,390.00,1360.0,Millions,INR
24,110,Bajirao Mastani,Bollywood,Hindi,2015,7.2,NaN,1.40,3.5,Billions,INR
25,128,Taare Zameen Par,Bollywood,Hindi,2007,8.3,NaN,120.00,1350.0,Millions,INR
26,129,Munna Bhai M.B.B.S.,Bollywood,Hindi,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR
27,130,PK,Bollywood,Hindi,2014,8.1,Vinod Chopra Films,850.00,8540.0,Millions,INR
28,131,Sanju,Bollywood,Hindi,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR
29,135,The Kashmir Files,Bollywood,Hindi,2022,8.3,Zee Studios,250.00,3409.0,Millions,INR
30,136,Bajrangi Bhaijaan,Bollywood,Hindi,2015,8.1,Salman Khan Films,900.00,11690.0,Millions,INR
31,139,Race 3,Bollywood,Hindi,2018,1.9,Salman Khan Films,1.80,3.1,Billions,INR
32,140,Shershaah,Bollywood,Hindi,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR
33,127,Pather Panchali,Bollywood,Bengali,1955,8.3,Government of West Bengal,70000.00,100000.0,Thousands,INR
34,132,Pushpa: The Rise - Part 1,Bollywood,Telugu,2021,7.6,Mythri Movie Makers,2.00,3.6,Billions,INR
35,133,RRR,Bollywood,Telugu,2022,8.0,DVV Entertainment,5.50,12.0,Billions,INR
36,134,Baahubali: The Beginning,Bollywood,Telugu,2015,8.0,Arka Media Works,1.80,6.5,Billions,INR

In [21]:
g = df.groupby('industry')
g.size()

industry
Bollywood    17
Hollywood    20
dtype: int64

In [23]:
for industry,data in g:
  if industry == 'Bollywood':
    print(industry,"\n",data)

Bollywood
     movie_id                        title   industry language  release_year  \
0        101             K.G.F: Chapter 2  Bollywood  Kannada          2022
21       107  Dilwale Dulhania Le Jayenge  Bollywood    Hindi          1995
22       108                     3 Idiots  Bollywood    Hindi          2009
23       109     Kabhi Khushi Kabhie Gham  Bollywood    Hindi          2001
24       110             Bajirao Mastani   Bollywood    Hindi          2015
25       128             Taare Zameen Par  Bollywood    Hindi          2007
26       129          Munna Bhai M.B.B.S.  Bollywood    Hindi          2003
27       130                           PK  Bollywood    Hindi          2014
28       131                        Sanju  Bollywood    Hindi          2018
29       135            The Kashmir Files  Bollywood    Hindi          2022
30       136            Bajrangi Bhaijaan  Bollywood    Hindi          2015
31       139                       Race 3  Bollywood    Hindi          2018
32       140                    Shershaah  Bollywood    Hindi          2021
33       127              Pather Panchali  Bollywood  Bengali          1955
34       132    Pushpa: The Rise - Part 1  Bollywood   Telugu          2021
35       133                          RRR  Bollywood   Telugu          2022
36       134     Baahubali: The Beginning  Bollywood   Telugu          2015

    imdb_rating                     studio   budget   revenue       unit  \
0           8.4              Hombale Films      1.0      12.5   Billions
21          8.0             Yash Raj Films    400.0    2000.0   Millions
22          8.4         Vinod Chopra Films    550.0    4000.0   Millions
23          7.4         Dharma Productions    390.0    1360.0   Millions
24          7.2                        NaN      1.4       3.5   Billions
25          8.3                        NaN    120.0    1350.0   Millions
26          8.1   Vinod Chopra Productions    100.0     410.0   Millions
27          8.1         Vinod Chopra Films    850.0    8540.0   Millions
28          NaN         Vinod Chopra Films      1.0       5.9   Billions
29          8.3                Zee Studios    250.0    3409.0   Millions
30          8.1          Salman Khan Films    900.0   11690.0   Millions
31          1.9          Salman Khan Films      1.8       3.1   Billions
32          8.4         Dharma Productions    500.0     950.0   Millions
33          8.3  Government of West Bengal  70000.0  100000.0  Thousands
34          7.6        Mythri Movie Makers      2.0       3.6   Billions
35          8.0          DVV Entertainment      5.5      12.0   Billions
36          8.0           Arka Media Works      1.8       6.5   Billions

   currency
0       INR
21      INR
22      INR
23      INR
24      INR
25      INR
26      INR
27      INR
28      INR
29      INR
30      INR
31      INR
32      INR
33      INR
34      INR
35      INR
36      INR

In [26]:
def grouper(df, idx, col):
  if 1 <= df[col][idx] <= 3.9:
    return 'Poor'
  elif 4 <= df[col][idx] <= 7.9:
    return 'Average'
  elif 8 <= df[col][idx] <= 10:
    return 'Good'
  else:
    return 'others'

In [31]:
g = df.groupby(lambda idx: grouper(df,idx,'imdb_rating'))
for key,data in g:
  print('Key : ', key)
  print('Data : \n',data)

Key :  Average
Data :
     movie_id                                        title   industry language  \
1        102  Doctor Strange in the Multiverse of Madness  Hollywood  English
2        103                        Thor: The Dark World   Hollywood  English
3        104                              Thor: Ragnarok   Hollywood  English
4        105                      Thor: Love and Thunder   Hollywood  English
9        117                                      Titanic  Hollywood  English
11       119                                       Avatar  Hollywood  English
19       137           Captain America: The First Avenger  Hollywood  English
20       138          Captain America: The Winter Soldier  Hollywood  English
23       109                     Kabhi Khushi Kabhie Gham  Bollywood    Hindi
24       110                             Bajirao Mastani   Bollywood    Hindi
34       132                    Pushpa: The Rise - Part 1  Bollywood   Telugu

    release_year  imdb_rating               studio  budget  revenue      unit  \
1           2022          7.0       Marvel Studios   200.0    954.8  Millions
2           2013          6.8       Marvel Studios   165.0    644.8  Millions
3           2017          7.9       Marvel Studios   180.0    854.0  Millions
4           2022          6.8       Marvel Studios   250.0    670.0  Millions
9           1997          7.9   Paramount Pictures   200.0   2202.0  Millions
11          2009          7.8     20th Century Fox   237.0   2847.0  Millions
19          2011          6.9       Marvel Studios   216.7    370.6  Millions
20          2014          7.8       Marvel Studios   177.0    714.4  Millions
23          2001          7.4   Dharma Productions   390.0   1360.0  Millions
24          2015          7.2                  NaN     1.4      3.5  Billions
34          2021          7.6  Mythri Movie Makers     2.0      3.6  Billions

   currency
1       USD
2       USD
3       USD
4       USD
9       USD
11      USD
19      USD
20      USD
23      INR
24      INR
34      INR
Key :  Good
Data :
     movie_id                        title   industry language  release_year  \
0        101             K.G.F: Chapter 2  Bollywood  Kannada          2022
5        111     The Shawshank Redemption  Hollywood  English          1994
6        113                 Interstellar  Hollywood  English          2014
7        115     The Pursuit of Happyness  Hollywood  English          2006
8        116                    Gladiator  Hollywood  English          2000
10       118        It's a Wonderful Life  Hollywood  English          1946
12       120                The Godfather  Hollywood  English          1972
13       121              The Dark Knight  Hollywood  English          2008
14       122             Schindler's List  Hollywood  English          1993
15       123                Jurassic Park  Hollywood  English          1993
16       124                     Parasite  Hollywood  English          2019
17       125            Avengers: Endgame  Hollywood  English          2019
18       126       Avengers: Infinity War  Hollywood  English          2018
21       107  Dilwale Dulhania Le Jayenge  Bollywood    Hindi          1995
22       108                     3 Idiots  Bollywood    Hindi          2009
25       128             Taare Zameen Par  Bollywood    Hindi          2007
26       129          Munna Bhai M.B.B.S.  Bollywood    Hindi          2003
27       130                           PK  Bollywood    Hindi          2014
29       135            The Kashmir Files  Bollywood    Hindi          2022
30       136            Bajrangi Bhaijaan  Bollywood    Hindi          2015
32       140                    Shershaah  Bollywood    Hindi          2021
33       127              Pather Panchali  Bollywood  Bengali          1955
35       133                          RRR  Bollywood   Telugu          2022
36       134     Baahubali: The Beginning  Bollywood   Telugu          2015

    imdb_rating                     studio    budget   revenue       unit  \
0           8.4              Hombale Films      1.00      12.5   Billions
5           9.3  Castle Rock Entertainment     25.00      73.3   Millions
6           8.6      Warner Bros. Pictures    165.00     701.8   Millions
7           8.0          Columbia Pictures     55.00     307.1   Millions
8           8.5       Universal Pictures      103.00     460.5   Millions
10          8.6              Liberty Films      3.18       3.3   Millions
12          9.2         Paramount Pictures      7.20     291.0   Millions
13          9.0                    Syncopy    185.00    1006.0   Millions
14          9.0         Universal Pictures     22.00     322.2   Millions
15          8.2         Universal Pictures     63.00    1046.0   Millions
16          8.5                        NaN     15.50     263.1   Millions
17          8.4             Marvel Studios    400.00    2798.0   Millions
18          8.4             Marvel Studios    400.00    2048.0   Millions
21          8.0             Yash Raj Films    400.00    2000.0   Millions
22          8.4         Vinod Chopra Films    550.00    4000.0   Millions
25          8.3                        NaN    120.00    1350.0   Millions
26          8.1   Vinod Chopra Productions    100.00     410.0   Millions
27          8.1         Vinod Chopra Films    850.00    8540.0   Millions
29          8.3                Zee Studios    250.00    3409.0   Millions
30          8.1          Salman Khan Films    900.00   11690.0   Millions
32          8.4         Dharma Productions    500.00     950.0   Millions
33          8.3  Government of West Bengal  70000.00  100000.0  Thousands
35          8.0          DVV Entertainment      5.50      12.0   Billions
36          8.0           Arka Media Works      1.80       6.5   Billions

   currency
0       INR
5       USD
6       USD
7       USD
8       USD
10      USD
12      USD
13      USD
14      USD
15      USD
16      USD
17      USD
18      USD
21      INR
22      INR
25      INR
26      INR
27      INR
29      INR
30      INR
32      INR
33      INR
35      INR
36      INR
Key :  Poor
Data :
     movie_id   title   industry language  release_year  imdb_rating  \
31       139  Race 3  Bollywood    Hindi          2018          1.9

               studio  budget  revenue      unit currency
31  Salman Khan Films     1.8      3.1  Billions      INR
Key :  others
Data :
     movie_id  title   industry language  release_year  imdb_rating  \
28       131  Sanju  Bollywood    Hindi          2018          NaN

                studio  budget  revenue      unit currency
28  Vinod Chopra Films     1.0      5.9  Billions      INR