<a href="https://colab.research.google.com/github/devmofizur/Python/blob/main/Pandas/Handle_Missing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
from google.colab import drive
import shutil
import os

drive.mount('/content/drive')

source_path = '/content/drive/MyDrive/Colab Notebooks/ML Learning/weather_data.csv'
destination_path = '/content/weather_data.csv'

if os.path.exists(source_path):
    shutil.copy(source_path, destination_path)
    print(f"Successfully copied '{source_path}' to '{destination_path}'")
else:
    print(f"Error: Source file '{source_path}' not found.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Successfully copied '/content/drive/MyDrive/Colab Notebooks/ML Learning/weather_data.csv' to '/content/weather_data.csv'

In [42]:
import pandas as pd

In [43]:
df = pd.read_csv('weather_data.csv')
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [44]:
df = df.fillna(
    {
        'temperature': df['temperature'].mean(),
        'windspeed': df['windspeed'].mean(),
        'event': 'No entry'
    }
)
df

         day  temperature  windspeed     event
0   1/1/2017        32.00       6.00      Rain
1   1/4/2017        33.22       9.00     Sunny
2   1/5/2017        28.00       8.42      Snow
3   1/6/2017        33.22       7.00  No entry
4   1/7/2017        32.00       8.42      Rain
5   1/8/2017        33.22       8.42     Sunny
6   1/9/2017        33.22       8.42  No entry
7  1/10/2017        34.10       8.10    Cloudy
8  1/11/2017        40.00      12.00     Sunny

In [48]:
df = pd.read_csv('weather_data.csv')
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [49]:
df.ffill()

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         32.0        9.0   Sunny
2   1/5/2017         28.0        9.0    Snow
3   1/6/2017         28.0        7.0    Snow
4   1/7/2017         32.0        7.0    Rain
5   1/8/2017         32.0        7.0   Sunny
6   1/9/2017         32.0        7.0   Sunny
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [50]:
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [51]:
df.bfill()

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         28.0        9.0   Sunny
2   1/5/2017         28.0        7.0    Snow
3   1/6/2017         32.0        7.0    Rain
4   1/7/2017         32.0        8.1    Rain
5   1/8/2017         34.1        8.1   Sunny
6   1/9/2017         34.1        8.1  Cloudy
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [52]:
df.ffill(limit=1)

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         32.0        9.0   Sunny
2   1/5/2017         28.0        9.0    Snow
3   1/6/2017         28.0        7.0    Snow
4   1/7/2017         32.0        7.0    Rain
5   1/8/2017         32.0        NaN   Sunny
6   1/9/2017          NaN        NaN   Sunny
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [53]:
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [55]:
df.interpolate()

/tmp/ipykernel_7379/4002874584.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

         day  temperature  windspeed   event
0   1/1/2017         32.0      6.000    Rain
1   1/4/2017         30.0      9.000   Sunny
2   1/5/2017         28.0      8.000    Snow
3   1/6/2017         30.0      7.000     NaN
4   1/7/2017         32.0      7.275    Rain
5   1/8/2017         32.7      7.550   Sunny
6   1/9/2017         33.4      7.825     NaN
7  1/10/2017         34.1      8.100  Cloudy
8  1/11/2017         40.0     12.000   Sunny

In [56]:
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [71]:
df.dropna()

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [75]:
df.dropna(thresh=3) # row will only be kept if it has at least 3 non-NaN value

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
4   1/7/2017         32.0        NaN    Rain
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [76]:
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny