<a href="https://colab.research.google.com/github/devmofizur/Python/blob/test/Pandas/Handle_Missing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Practice**

In [150]:
from google.colab import drive
import shutil
import os

drive.mount('/content/drive')

source_path = '/content/drive/MyDrive/Colab Notebooks/ML Learning/weather_data.csv'
destination_path = '/content/weather_data.csv'

if os.path.exists(source_path):
    shutil.copy(source_path, destination_path)
    print(f"Successfully copied '{source_path}' to '{destination_path}'")
else:
    print(f"Error: Source file '{source_path}' not found.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Successfully copied '/content/drive/MyDrive/Colab Notebooks/ML Learning/weather_data.csv' to '/content/weather_data.csv'

In [151]:
import pandas as pd

In [152]:
df = pd.read_csv('weather_data.csv')
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [153]:
df = df.fillna(
    {
        'temperature': df['temperature'].mean(),
        'windspeed': df['windspeed'].mean(),
        'event': 'No entry'
    }
)
df

         day  temperature  windspeed     event
0   1/1/2017        32.00       6.00      Rain
1   1/4/2017        33.22       9.00     Sunny
2   1/5/2017        28.00       8.42      Snow
3   1/6/2017        33.22       7.00  No entry
4   1/7/2017        32.00       8.42      Rain
5   1/8/2017        33.22       8.42     Sunny
6   1/9/2017        33.22       8.42  No entry
7  1/10/2017        34.10       8.10    Cloudy
8  1/11/2017        40.00      12.00     Sunny

In [154]:
df = pd.read_csv('weather_data.csv')
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [155]:
df.ffill()

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         32.0        9.0   Sunny
2   1/5/2017         28.0        9.0    Snow
3   1/6/2017         28.0        7.0    Snow
4   1/7/2017         32.0        7.0    Rain
5   1/8/2017         32.0        7.0   Sunny
6   1/9/2017         32.0        7.0   Sunny
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [156]:
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [157]:
df.bfill()

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         28.0        9.0   Sunny
2   1/5/2017         28.0        7.0    Snow
3   1/6/2017         32.0        7.0    Rain
4   1/7/2017         32.0        8.1    Rain
5   1/8/2017         34.1        8.1   Sunny
6   1/9/2017         34.1        8.1  Cloudy
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [158]:
df.ffill(limit=1)

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         32.0        9.0   Sunny
2   1/5/2017         28.0        9.0    Snow
3   1/6/2017         28.0        7.0    Snow
4   1/7/2017         32.0        7.0    Rain
5   1/8/2017         32.0        NaN   Sunny
6   1/9/2017          NaN        NaN   Sunny
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [159]:
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [160]:
df.interpolate()

/tmp/ipykernel_5487/4002874584.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

         day  temperature  windspeed   event
0   1/1/2017         32.0      6.000    Rain
1   1/4/2017         30.0      9.000   Sunny
2   1/5/2017         28.0      8.000    Snow
3   1/6/2017         30.0      7.000     NaN
4   1/7/2017         32.0      7.275    Rain
5   1/8/2017         32.7      7.550   Sunny
6   1/9/2017         33.4      7.825     NaN
7  1/10/2017         34.1      8.100  Cloudy
8  1/11/2017         40.0     12.000   Sunny

In [161]:
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [162]:
df.dropna()

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [163]:
df.dropna(thresh=3) # Row will only be kept if it has at least 3 non-NaN values.

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
4   1/7/2017         32.0        NaN    Rain
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [164]:
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

## **Exercise**
Question : [See](https://drive.google.com/file/d/1zFG0fW2b4quJ4BGTSNPOnOaxKaN42kaI/view?usp=sharing)

In [165]:
from google.colab import drive
import shutil
import os

drive.mount('/content/drive')

source_path = '/content/drive/MyDrive/Colab Notebooks/ML Learning/fruits_data.csv'
destination_path = '/content/fruits_data.csv'

if os.path.exists(source_path):
    shutil.copy(source_path, destination_path)
    print(f"Successfully copied '{source_path}' to '{destination_path}'")
else:
    print(f"Error: Source file '{source_path}' not found.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Successfully copied '/content/drive/MyDrive/Colab Notebooks/ML Learning/fruits_data.csv' to '/content/fruits_data.csv'

In [166]:
import pandas as pd

df = pd.read_csv('fruits_data.csv')

In [167]:
df.shape

(10, 6)

In [168]:
column_names = list(df.columns)
column_names

['date',
 'apple(1kg)',
 'banana(1 dozen)',
 'grapes(1kg)',
 'mango(1kg)',
 'Water Melons(1)']

In [169]:
df

,date,apple(1kg),banana(1 dozen),grapes(1kg),mango(1kg),Water Melons(1)
0,01-01-2022,230.0,46.0,65.0,184.0,NaN
1,01-02-2022,237.0,50.0,72.0,173.0,72.0
2,01-03-2022,259.0,NaN,NaN,NaN,93.0
3,01-04-2022,NaN,41.0,75.0,175.0,74.0
4,01-05-2022,240.0,48.0,NaN,185.0,84.0
5,01-06-2022,234.0,45.0,66.0,194.0,93.0
6,01-07-2022,NaN,NaN,70.0,174.0,NaN
7,01-08-2022,236.0,46.0,66.0,187.0,86.0
8,01-09-2022,232.0,41.0,71.0,NaN,93.0
9,01-10-2022,240.0,48.0,NaN,198.0,97.0

In [170]:
new_df = df.fillna(-1)
new_df

,date,apple(1kg),banana(1 dozen),grapes(1kg),mango(1kg),Water Melons(1)
0,01-01-2022,230.0,46.0,65.0,184.0,-1.0
1,01-02-2022,237.0,50.0,72.0,173.0,72.0
2,01-03-2022,259.0,-1.0,-1.0,-1.0,93.0
3,01-04-2022,-1.0,41.0,75.0,175.0,74.0
4,01-05-2022,240.0,48.0,-1.0,185.0,84.0
5,01-06-2022,234.0,45.0,66.0,194.0,93.0
6,01-07-2022,-1.0,-1.0,70.0,174.0,-1.0
7,01-08-2022,236.0,46.0,66.0,187.0,86.0
8,01-09-2022,232.0,41.0,71.0,-1.0,93.0
9,01-10-2022,240.0,48.0,-1.0,198.0,97.0

In [171]:
new_df = df.fillna(
    {
        'apple(1kg)': df['apple(1kg)'].mean(),
        'banana(1 dozen)': df['banana(1 dozen)'].mean(),
        'grapes(1kg)': df['grapes(1kg)'].median(),
        'mango(1kg)': df['mango(1kg)'].median(),
        'Water Melons(1)': 'Not Available'
    }
)
new_df

,date,apple(1kg),banana(1 dozen),grapes(1kg),mango(1kg),Water Melons(1)
0,01-01-2022,230.0,46.000,65.0,184.0,Not Available
1,01-02-2022,237.0,50.000,72.0,173.0,72.0
2,01-03-2022,259.0,45.625,70.0,184.5,93.0
3,01-04-2022,238.5,41.000,75.0,175.0,74.0
4,01-05-2022,240.0,48.000,70.0,185.0,84.0
5,01-06-2022,234.0,45.000,66.0,194.0,93.0
6,01-07-2022,238.5,45.625,70.0,174.0,Not Available
7,01-08-2022,236.0,46.000,66.0,187.0,86.0
8,01-09-2022,232.0,41.000,71.0,184.5,93.0
9,01-10-2022,240.0,48.000,70.0,198.0,97.0

In [172]:
new_df = df.ffill()
new_df

,date,apple(1kg),banana(1 dozen),grapes(1kg),mango(1kg),Water Melons(1)
0,01-01-2022,230.0,46.0,65.0,184.0,NaN
1,01-02-2022,237.0,50.0,72.0,173.0,72.0
2,01-03-2022,259.0,50.0,72.0,173.0,93.0
3,01-04-2022,259.0,41.0,75.0,175.0,74.0
4,01-05-2022,240.0,48.0,75.0,185.0,84.0
5,01-06-2022,234.0,45.0,66.0,194.0,93.0
6,01-07-2022,234.0,45.0,70.0,174.0,93.0
7,01-08-2022,236.0,46.0,66.0,187.0,86.0
8,01-09-2022,232.0,41.0,71.0,187.0,93.0
9,01-10-2022,240.0,48.0,71.0,198.0,97.0

In [173]:
new_df = df.dropna(thresh=4)
new_df

,date,apple(1kg),banana(1 dozen),grapes(1kg),mango(1kg),Water Melons(1)
0,01-01-2022,230.0,46.0,65.0,184.0,NaN
1,01-02-2022,237.0,50.0,72.0,173.0,72.0
3,01-04-2022,NaN,41.0,75.0,175.0,74.0
4,01-05-2022,240.0,48.0,NaN,185.0,84.0
5,01-06-2022,234.0,45.0,66.0,194.0,93.0
7,01-08-2022,236.0,46.0,66.0,187.0,86.0
8,01-09-2022,232.0,41.0,71.0,NaN,93.0
9,01-10-2022,240.0,48.0,NaN,198.0,97.0

In [174]:
new_df = df.dropna()
new_df

,date,apple(1kg),banana(1 dozen),grapes(1kg),mango(1kg),Water Melons(1)
1,01-02-2022,237.0,50.0,72.0,173.0,72.0
5,01-06-2022,234.0,45.0,66.0,194.0,93.0
7,01-08-2022,236.0,46.0,66.0,187.0,86.0

In [175]:
new_df.to_csv('final_data.csv', index= False)

## **Replace**

In [176]:
df = pd.read_csv('weather_data.csv')
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [177]:
df.replace( np.nan , value = -99999)

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017     -99999.0        9.0   Sunny
2   1/5/2017         28.0   -99999.0    Snow
3   1/6/2017     -99999.0        7.0  -99999
4   1/7/2017         32.0   -99999.0    Rain
5   1/8/2017     -99999.0   -99999.0   Sunny
6   1/9/2017     -99999.0   -99999.0  -99999
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [185]:
df['score'] = df['event'].replace(['Rain','Sunny','Snow','Cloudy'] , [1,2,3,4])
df

/tmp/ipykernel_5487/1988246735.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['score'] = df['event'].replace(['Rain','Sunny','Snow','Cloudy'] , [1,2,3,4])

         day  temperature  windspeed   event  score
0   1/1/2017         32.0        6.0    Rain    1.0
1   1/4/2017          NaN        9.0   Sunny    2.0
2   1/5/2017         28.0        NaN    Snow    3.0
3   1/6/2017          NaN        7.0     NaN    NaN
4   1/7/2017         32.0        NaN    Rain    1.0
5   1/8/2017          NaN        NaN   Sunny    2.0
6   1/9/2017          NaN        NaN     NaN    NaN
7  1/10/2017         34.1        8.1  Cloudy    4.0
8  1/11/2017         40.0       12.0   Sunny    2.0

## **Exercise on Replace**
Question : [See](https://drive.google.com/file/d/1_ZkbncC1vt-GfPNiO4ZoRVI9SPQ0GoFW/view?usp=sharing)

In [186]:
from google.colab import drive
import shutil
import os

drive.mount('/content/drive')

source_path = '/content/drive/MyDrive/Colab Notebooks/ML Learning/food_db.csv'
destination_path = '/content/food_db.csv'

if os.path.exists(source_path):
    shutil.copy(source_path, destination_path)
    print(f"Successfully copied '{source_path}' to '{destination_path}'")
else:
    print(f"Error: Source file '{source_path}' not found.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Successfully copied '/content/drive/MyDrive/Colab Notebooks/ML Learning/food_db.csv' to '/content/food_db.csv'

In [219]:
import pandas as pd

df = pd.read_csv('food_db.csv')

In [220]:
df.shape

(10, 5)

In [221]:
df

   food_id            name discount   price     rating
0        1  Butter Chicken      10%  $12.99  Excellent
1        2     Masala Dosa       5%   $7.50       Good
2        3         Biryani      15%  $15.99  Excellent
3        4           Chaat      20%   $3.99    Average
4        5         Samosas      10%   $2.50       Good
5        6   Chole Bhature       5%   $8.99  Excellent
6        7    Paneer Tikka      10%  $10.99  Very Good
7        8     Idli-Sambar      15%   $6.99       Good
8        9      Rogan Josh      10%  $16.99  Excellent
9       10           Lassi       5%   $3.50    Average

In [227]:
new_df = df.replace(['5%','10%'], '13%' )
new_df

   food_id            name discount   price     rating
0        1  Butter Chicken      13%  $12.99  Excellent
1        2     Masala Dosa      13%   $7.50       Good
2        3         Biryani      15%  $15.99  Excellent
3        4           Chaat      20%   $3.99    Average
4        5         Samosas      13%   $2.50       Good
5        6   Chole Bhature      13%   $8.99  Excellent
6        7    Paneer Tikka      13%  $10.99  Very Good
7        8     Idli-Sambar      15%   $6.99       Good
8        9      Rogan Josh      13%  $16.99  Excellent
9       10           Lassi      13%   $3.50    Average

In [228]:
new_df = df.replace({
    'Excellent': 4, 'Very Good': 3, 'Good': 2, 'Average': 1
})
new_df

/tmp/ipykernel_5487/3059545945.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new_df = df.replace({

   food_id            name discount   price  rating
0        1  Butter Chicken      10%  $12.99       4
1        2     Masala Dosa       5%   $7.50       2
2        3         Biryani      15%  $15.99       4
3        4           Chaat      20%   $3.99       1
4        5         Samosas      10%   $2.50       2
5        6   Chole Bhature       5%   $8.99       4
6        7    Paneer Tikka      10%  $10.99       3
7        8     Idli-Sambar      15%   $6.99       2
8        9      Rogan Josh      10%  $16.99       4
9       10           Lassi       5%   $3.50       1